#!/bin/bash

sqlite3 index-nu.db << END_SQL
PRAGMA foreign_keys=OFF;

BEGIN TRANSACTION;

CREATE TABLE new_BlkID (
        id INTEGER PRIMARY KEY, 
        blkhash TEXT NOT NULL);
CREATE TABLE new_TxID (
        id INTEGER PRIMARY KEY, 
        txhash TEXT NOT NULL);
CREATE TABLE new_AddrID (
        id INTEGER PRIMARY KEY, 
        addr TEXT NOT NULL);

INSERT INTO new_BlkID (blkhash)
        SELECT DISTINCT blkhash FROM BlkID ORDER BY id ASC;
INSERT INTO new_TxID (txhash)
        SELECT DISTINCT txhash FROM TxID ORDER BY id ASC;
INSERT INTO new_AddrID (addr)
        SELECT DISTINCT addr FROM AddrID ORDER BY id ASC;

DROP TABLE BlkID;
DROP TABLE TxID;
DROP TABLE AddrID;

ALTER TABLE new_BlkID RENAME TO BlkID;
ALTER TABLE new_TxID RENAME TO TxID;
ALTER TABLE new_AddrID RENAME TO AddrID;

COMMIT TRANSACTION;
PRAGMA foreign_keys=ON;
END_SQL
