#!/bin/bash

cd /opt/bitsql_venv
source bin/activate

cd /opt/bitsql
/opt/bitsql_venv/bin/gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --chdir [PATH] --bind 0.0.0.0:8888 main:app
